name = "Kanso Ink Obsidian"
background = "#14171d"
foreground = "#c5c9c7"
cursor = "#c5c9c7"
cursor_text = "#14171d"
selection_background = "#22262d"
selection_foreground = "#c5c9c7"
ansi0 = "#1B1E23"
ansi1 = "#B78383"
ansi2 = "#879A89"
ansi3 = "#8F8B78"
ansi4 = "#8293A3"
ansi5 = "#948A95"
ansi6 = "#7E9292"
ansi7 = "#B8BCBA"
ansi8 = "#626872"
ansi9 = "#C49393"
ansi10 = "#9AAA9C"
ansi11 = "#AAA58F"
ansi12 = "#96A6B3"
ansi13 = "#A69CA6"
ansi14 = "#91A5A5"
ansi15 = "#D6D8D6"
